version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverse-proxy
  backend_user:
    build:
      context: ./udagram-api-user
    image: backend-api-user
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: backend-api-feed
  frontend:
    build:
      context: ./udagram-frontend
    image: frontend