apiVersion: apps/v1
metadata:
  name: backend-feed
  labels:
    app: backend-feed
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        imagePullPolicy: Always
        image: mei2k0809/backend-api-feed:v1
        resources:
          requests:
            memory: "1024Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"
        envFrom:
          - configMapRef:
              name: env-configmap
        ports:
          - containerPort: 8080 