apiVersion: v1
metadata:
  name: backend-feed
  labels:
    app: backend-feed
kind: Service
spec: 
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: backend-feed