name: udagram-ci
on: 
  push: 
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build Docker images
        run: docker-compose -f docker-compose-build.yaml build --paralle

      - name: List Docker images
        run: docker images

      - name: Push Docker images
        run: |
          docker tag reverse-proxy ${{ secrets.DOCKERHUB_USERNAME }}/reverse-proxy:v1
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/reverse-proxy:v1
          docker tag backend-api-user ${{ secrets.DOCKERHUB_USERNAME }}/backend-api-user:v1
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend-api-user:v1
          docker tag backend-api-feed ${{ secrets.DOCKERHUB_USERNAME }}/backend-api-feed:v1
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend-api-feed:v1
          docker tag frontend ${{ secrets.DOCKERHUB_USERNAME }}/frontend:local
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:local